#!/bin/sh
# QIIME 1.6.0 75165190e39897f1b873f79f5528f1de8f711334
# smp

make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.forehead_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_avg --vectors_algorithm avg -o /Users/yoshikivazquezbaeza/smp/pc_forehead_avg
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.forehead_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_diff --vectors_algorithm diff -o /Users/yoshikivazquezbaeza/smp/pc_forehead_diff
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.forehead_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_trajectory --vectors_algorithm trajectory -o /Users/yoshikivazquezbaeza/smp/pc_forehead_trajectory
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.forehead_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_wdiff --vectors_algorithm wdiff -o /Users/yoshikivazquezbaeza/smp/pc_forehead_wdiff --window_size 2
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.gut_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_avg --vectors_algorithm avg -o /Users/yoshikivazquezbaeza/smp/pc_gut_avg
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.gut_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_diff --vectors_algorithm diff -o /Users/yoshikivazquezbaeza/smp/pc_gut_diff
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.gut_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_trajectory --vectors_algorithm trajectory -o /Users/yoshikivazquezbaeza/smp/pc_gut_trajectory
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.gut_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_wdiff --vectors_algorithm wdiff -o /Users/yoshikivazquezbaeza/smp/pc_gut_wdiff --window_size 2
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.palm_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_avg --vectors_algorithm avg -o /Users/yoshikivazquezbaeza/smp/pc_palm_avg
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.palm_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_diff --vectors_algorithm diff -o /Users/yoshikivazquezbaeza/smp/pc_palm_diff
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.palm_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_trajectory --vectors_algorithm trajectory -o /Users/yoshikivazquezbaeza/smp/pc_palm_trajectory
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.palm_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_wdiff --vectors_algorithm wdiff -o /Users/yoshikivazquezbaeza/smp/pc_palm_wdiff --window_size 2
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.tongue_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_avg --vectors_algorithm avg -o /Users/yoshikivazquezbaeza/smp/pc_tongue_avg
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.tongue_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_diff --vectors_algorithm diff -o /Users/yoshikivazquezbaeza/smp/pc_tongue_diff
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.tongue_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_trajectory --vectors_algorithm trajectory -o /Users/yoshikivazquezbaeza/smp/pc_tongue_trajectory
make_3d_plots.py -i /scratch/yoshiki/smp/beta-diversity/pc_unweighted_unifrac_dm.tongue_ts_only.txt -m /scratch/yoshiki/smp/mapping_file.txt -a WeeksSinceStart --add_vectors=SiteID,WeeksSinceStart --vectors_path vectors_output_wdiff --vectors_algorithm wdiff -o /Users/yoshikivazquezbaeza/smp/pc_tongue_wdiff --window_size 2
